app:
  version: 1.0.0

environment: default

ga:
  viewId: "123808379"

clickhouse:
  type: clickhouse
  credentials: >
    {
      "host": "localhost",
      "port": 8123,
      "user": "test",
      "password": "qwerty-321",
      "queryOptions": {
        "profile": "readwrite",
        "database": "GA-reporting"
      }
    }
