app:
  version: 1.0.0

environment: default

reporting_server:
  port: 8080

ga:
  viewId: "123808379"

clickhouse:
  type: clickhouse
  credentials: >
    {
      "host": "localhost",
      "port": 8123,
      "user": "testu1",
      "password": "qwerty-321",
      "queryOptions": {
        "profile": "readwrite",
        "database": "GA_Reporting"
      }
    }
